/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.focaplo.supverinventory.rpc;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;

public class InventoryLookUpResponse implements TBase<InventoryLookUpResponse._Fields>, java.io.Serializable, Cloneable, Comparable<InventoryLookUpResponse> {
  private static final TStruct STRUCT_DESC = new TStruct("InventoryLookUpResponse");

  private static final TField UID_FIELD_DESC = new TField("uid", TType.I32, (short)1);
  private static final TField ITEM_NUMBER_FIELD_DESC = new TField("itemNumber", TType.STRING, (short)2);
  private static final TField QUANTITY_ON_HAND_FIELD_DESC = new TField("quantityOnHand", TType.I32, (short)3);

  public int uid;
  public String itemNumber;
  public int quantityOnHand;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    UID((short)1, "uid"),
    ITEM_NUMBER((short)2, "itemNumber"),
    QUANTITY_ON_HAND((short)3, "quantityOnHand");

    private static final Map<Integer, _Fields> byId = new HashMap<Integer, _Fields>();
    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byId.put((int)field._thriftId, field);
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      return byId.get(fieldId);
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __UID_ISSET_ID = 0;
  private static final int __QUANTITYONHAND_ISSET_ID = 1;
  private BitSet __isset_bit_vector = new BitSet(2);

  public static final Map<_Fields, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new EnumMap<_Fields, FieldMetaData>(_Fields.class) {{
    put(_Fields.UID, new FieldMetaData("uid", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I32)));
    put(_Fields.ITEM_NUMBER, new FieldMetaData("itemNumber", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    put(_Fields.QUANTITY_ON_HAND, new FieldMetaData("quantityOnHand", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I32)));
  }});

  static {
    FieldMetaData.addStructMetaDataMap(InventoryLookUpResponse.class, metaDataMap);
  }

  public InventoryLookUpResponse() {
  }

  public InventoryLookUpResponse(
    int uid,
    String itemNumber,
    int quantityOnHand)
  {
    this();
    this.uid = uid;
    setUidIsSet(true);
    this.itemNumber = itemNumber;
    this.quantityOnHand = quantityOnHand;
    setQuantityOnHandIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public InventoryLookUpResponse(InventoryLookUpResponse other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.uid = other.uid;
    if (other.isSetItemNumber()) {
      this.itemNumber = other.itemNumber;
    }
    this.quantityOnHand = other.quantityOnHand;
  }

  public InventoryLookUpResponse deepCopy() {
    return new InventoryLookUpResponse(this);
  }

  @Deprecated
  public InventoryLookUpResponse clone() {
    return new InventoryLookUpResponse(this);
  }

  public int getUid() {
    return this.uid;
  }

  public InventoryLookUpResponse setUid(int uid) {
    this.uid = uid;
    setUidIsSet(true);
    return this;
  }

  public void unsetUid() {
    __isset_bit_vector.clear(__UID_ISSET_ID);
  }

  /** Returns true if field uid is set (has been asigned a value) and false otherwise */
  public boolean isSetUid() {
    return __isset_bit_vector.get(__UID_ISSET_ID);
  }

  public void setUidIsSet(boolean value) {
    __isset_bit_vector.set(__UID_ISSET_ID, value);
  }

  public String getItemNumber() {
    return this.itemNumber;
  }

  public InventoryLookUpResponse setItemNumber(String itemNumber) {
    this.itemNumber = itemNumber;
    return this;
  }

  public void unsetItemNumber() {
    this.itemNumber = null;
  }

  /** Returns true if field itemNumber is set (has been asigned a value) and false otherwise */
  public boolean isSetItemNumber() {
    return this.itemNumber != null;
  }

  public void setItemNumberIsSet(boolean value) {
    if (!value) {
      this.itemNumber = null;
    }
  }

  public int getQuantityOnHand() {
    return this.quantityOnHand;
  }

  public InventoryLookUpResponse setQuantityOnHand(int quantityOnHand) {
    this.quantityOnHand = quantityOnHand;
    setQuantityOnHandIsSet(true);
    return this;
  }

  public void unsetQuantityOnHand() {
    __isset_bit_vector.clear(__QUANTITYONHAND_ISSET_ID);
  }

  /** Returns true if field quantityOnHand is set (has been asigned a value) and false otherwise */
  public boolean isSetQuantityOnHand() {
    return __isset_bit_vector.get(__QUANTITYONHAND_ISSET_ID);
  }

  public void setQuantityOnHandIsSet(boolean value) {
    __isset_bit_vector.set(__QUANTITYONHAND_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case UID:
      if (value == null) {
        unsetUid();
      } else {
        setUid((Integer)value);
      }
      break;

    case ITEM_NUMBER:
      if (value == null) {
        unsetItemNumber();
      } else {
        setItemNumber((String)value);
      }
      break;

    case QUANTITY_ON_HAND:
      if (value == null) {
        unsetQuantityOnHand();
      } else {
        setQuantityOnHand((Integer)value);
      }
      break;

    }
  }

  public void setFieldValue(int fieldID, Object value) {
    setFieldValue(_Fields.findByThriftIdOrThrow(fieldID), value);
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case UID:
      return new Integer(getUid());

    case ITEM_NUMBER:
      return getItemNumber();

    case QUANTITY_ON_HAND:
      return new Integer(getQuantityOnHand());

    }
    throw new IllegalStateException();
  }

  public Object getFieldValue(int fieldId) {
    return getFieldValue(_Fields.findByThriftIdOrThrow(fieldId));
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    switch (field) {
    case UID:
      return isSetUid();
    case ITEM_NUMBER:
      return isSetItemNumber();
    case QUANTITY_ON_HAND:
      return isSetQuantityOnHand();
    }
    throw new IllegalStateException();
  }

  public boolean isSet(int fieldID) {
    return isSet(_Fields.findByThriftIdOrThrow(fieldID));
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof InventoryLookUpResponse)
      return this.equals((InventoryLookUpResponse)that);
    return false;
  }

  public boolean equals(InventoryLookUpResponse that) {
    if (that == null)
      return false;

    boolean this_present_uid = true;
    boolean that_present_uid = true;
    if (this_present_uid || that_present_uid) {
      if (!(this_present_uid && that_present_uid))
        return false;
      if (this.uid != that.uid)
        return false;
    }

    boolean this_present_itemNumber = true && this.isSetItemNumber();
    boolean that_present_itemNumber = true && that.isSetItemNumber();
    if (this_present_itemNumber || that_present_itemNumber) {
      if (!(this_present_itemNumber && that_present_itemNumber))
        return false;
      if (!this.itemNumber.equals(that.itemNumber))
        return false;
    }

    boolean this_present_quantityOnHand = true;
    boolean that_present_quantityOnHand = true;
    if (this_present_quantityOnHand || that_present_quantityOnHand) {
      if (!(this_present_quantityOnHand && that_present_quantityOnHand))
        return false;
      if (this.quantityOnHand != that.quantityOnHand)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(InventoryLookUpResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    InventoryLookUpResponse typedOther = (InventoryLookUpResponse)other;

    lastComparison = Boolean.valueOf(isSetUid()).compareTo(typedOther.isSetUid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUid()) {      lastComparison = TBaseHelper.compareTo(uid, typedOther.uid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetItemNumber()).compareTo(typedOther.isSetItemNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetItemNumber()) {      lastComparison = TBaseHelper.compareTo(itemNumber, typedOther.itemNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQuantityOnHand()).compareTo(typedOther.isSetQuantityOnHand());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuantityOnHand()) {      lastComparison = TBaseHelper.compareTo(quantityOnHand, typedOther.quantityOnHand);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // UID
          if (field.type == TType.I32) {
            this.uid = iprot.readI32();
            setUidIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // ITEM_NUMBER
          if (field.type == TType.STRING) {
            this.itemNumber = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // QUANTITY_ON_HAND
          if (field.type == TType.I32) {
            this.quantityOnHand = iprot.readI32();
            setQuantityOnHandIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    oprot.writeFieldBegin(UID_FIELD_DESC);
    oprot.writeI32(this.uid);
    oprot.writeFieldEnd();
    if (this.itemNumber != null) {
      oprot.writeFieldBegin(ITEM_NUMBER_FIELD_DESC);
      oprot.writeString(this.itemNumber);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(QUANTITY_ON_HAND_FIELD_DESC);
    oprot.writeI32(this.quantityOnHand);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("InventoryLookUpResponse(");
    boolean first = true;

    sb.append("uid:");
    sb.append(this.uid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("itemNumber:");
    if (this.itemNumber == null) {
      sb.append("null");
    } else {
      sb.append(this.itemNumber);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("quantityOnHand:");
    sb.append(this.quantityOnHand);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

