/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.focaplo.supverinventory.rpc;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;

public class itemReservation implements TBase<itemReservation._Fields>, java.io.Serializable, Cloneable, Comparable<itemReservation> {
  private static final TStruct STRUCT_DESC = new TStruct("itemReservation");

  private static final TField UID_FIELD_DESC = new TField("uid", TType.I32, (short)1);
  private static final TField ITEM_NUMBER_FIELD_DESC = new TField("itemNumber", TType.STRING, (short)2);
  private static final TField RESERVE_QUANTITY_FIELD_DESC = new TField("reserveQuantity", TType.I32, (short)3);
  private static final TField ORDER_NUMBER_FIELD_DESC = new TField("orderNumber", TType.STRING, (short)4);
  private static final TField FROM_ID_FIELD_DESC = new TField("fromId", TType.STRING, (short)5);

  public int uid;
  public String itemNumber;
  public int reserveQuantity;
  public String orderNumber;
  public String fromId;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    UID((short)1, "uid"),
    ITEM_NUMBER((short)2, "itemNumber"),
    RESERVE_QUANTITY((short)3, "reserveQuantity"),
    ORDER_NUMBER((short)4, "orderNumber"),
    FROM_ID((short)5, "fromId");

    private static final Map<Integer, _Fields> byId = new HashMap<Integer, _Fields>();
    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byId.put((int)field._thriftId, field);
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      return byId.get(fieldId);
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __UID_ISSET_ID = 0;
  private static final int __RESERVEQUANTITY_ISSET_ID = 1;
  private BitSet __isset_bit_vector = new BitSet(2);

  public static final Map<_Fields, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new EnumMap<_Fields, FieldMetaData>(_Fields.class) {{
    put(_Fields.UID, new FieldMetaData("uid", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I32)));
    put(_Fields.ITEM_NUMBER, new FieldMetaData("itemNumber", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    put(_Fields.RESERVE_QUANTITY, new FieldMetaData("reserveQuantity", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I32)));
    put(_Fields.ORDER_NUMBER, new FieldMetaData("orderNumber", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    put(_Fields.FROM_ID, new FieldMetaData("fromId", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
  }});

  static {
    FieldMetaData.addStructMetaDataMap(itemReservation.class, metaDataMap);
  }

  public itemReservation() {
  }

  public itemReservation(
    int uid,
    String itemNumber,
    int reserveQuantity,
    String orderNumber,
    String fromId)
  {
    this();
    this.uid = uid;
    setUidIsSet(true);
    this.itemNumber = itemNumber;
    this.reserveQuantity = reserveQuantity;
    setReserveQuantityIsSet(true);
    this.orderNumber = orderNumber;
    this.fromId = fromId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public itemReservation(itemReservation other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.uid = other.uid;
    if (other.isSetItemNumber()) {
      this.itemNumber = other.itemNumber;
    }
    this.reserveQuantity = other.reserveQuantity;
    if (other.isSetOrderNumber()) {
      this.orderNumber = other.orderNumber;
    }
    if (other.isSetFromId()) {
      this.fromId = other.fromId;
    }
  }

  public itemReservation deepCopy() {
    return new itemReservation(this);
  }

  @Deprecated
  public itemReservation clone() {
    return new itemReservation(this);
  }

  public int getUid() {
    return this.uid;
  }

  public itemReservation setUid(int uid) {
    this.uid = uid;
    setUidIsSet(true);
    return this;
  }

  public void unsetUid() {
    __isset_bit_vector.clear(__UID_ISSET_ID);
  }

  /** Returns true if field uid is set (has been asigned a value) and false otherwise */
  public boolean isSetUid() {
    return __isset_bit_vector.get(__UID_ISSET_ID);
  }

  public void setUidIsSet(boolean value) {
    __isset_bit_vector.set(__UID_ISSET_ID, value);
  }

  public String getItemNumber() {
    return this.itemNumber;
  }

  public itemReservation setItemNumber(String itemNumber) {
    this.itemNumber = itemNumber;
    return this;
  }

  public void unsetItemNumber() {
    this.itemNumber = null;
  }

  /** Returns true if field itemNumber is set (has been asigned a value) and false otherwise */
  public boolean isSetItemNumber() {
    return this.itemNumber != null;
  }

  public void setItemNumberIsSet(boolean value) {
    if (!value) {
      this.itemNumber = null;
    }
  }

  public int getReserveQuantity() {
    return this.reserveQuantity;
  }

  public itemReservation setReserveQuantity(int reserveQuantity) {
    this.reserveQuantity = reserveQuantity;
    setReserveQuantityIsSet(true);
    return this;
  }

  public void unsetReserveQuantity() {
    __isset_bit_vector.clear(__RESERVEQUANTITY_ISSET_ID);
  }

  /** Returns true if field reserveQuantity is set (has been asigned a value) and false otherwise */
  public boolean isSetReserveQuantity() {
    return __isset_bit_vector.get(__RESERVEQUANTITY_ISSET_ID);
  }

  public void setReserveQuantityIsSet(boolean value) {
    __isset_bit_vector.set(__RESERVEQUANTITY_ISSET_ID, value);
  }

  public String getOrderNumber() {
    return this.orderNumber;
  }

  public itemReservation setOrderNumber(String orderNumber) {
    this.orderNumber = orderNumber;
    return this;
  }

  public void unsetOrderNumber() {
    this.orderNumber = null;
  }

  /** Returns true if field orderNumber is set (has been asigned a value) and false otherwise */
  public boolean isSetOrderNumber() {
    return this.orderNumber != null;
  }

  public void setOrderNumberIsSet(boolean value) {
    if (!value) {
      this.orderNumber = null;
    }
  }

  public String getFromId() {
    return this.fromId;
  }

  public itemReservation setFromId(String fromId) {
    this.fromId = fromId;
    return this;
  }

  public void unsetFromId() {
    this.fromId = null;
  }

  /** Returns true if field fromId is set (has been asigned a value) and false otherwise */
  public boolean isSetFromId() {
    return this.fromId != null;
  }

  public void setFromIdIsSet(boolean value) {
    if (!value) {
      this.fromId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case UID:
      if (value == null) {
        unsetUid();
      } else {
        setUid((Integer)value);
      }
      break;

    case ITEM_NUMBER:
      if (value == null) {
        unsetItemNumber();
      } else {
        setItemNumber((String)value);
      }
      break;

    case RESERVE_QUANTITY:
      if (value == null) {
        unsetReserveQuantity();
      } else {
        setReserveQuantity((Integer)value);
      }
      break;

    case ORDER_NUMBER:
      if (value == null) {
        unsetOrderNumber();
      } else {
        setOrderNumber((String)value);
      }
      break;

    case FROM_ID:
      if (value == null) {
        unsetFromId();
      } else {
        setFromId((String)value);
      }
      break;

    }
  }

  public void setFieldValue(int fieldID, Object value) {
    setFieldValue(_Fields.findByThriftIdOrThrow(fieldID), value);
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case UID:
      return new Integer(getUid());

    case ITEM_NUMBER:
      return getItemNumber();

    case RESERVE_QUANTITY:
      return new Integer(getReserveQuantity());

    case ORDER_NUMBER:
      return getOrderNumber();

    case FROM_ID:
      return getFromId();

    }
    throw new IllegalStateException();
  }

  public Object getFieldValue(int fieldId) {
    return getFieldValue(_Fields.findByThriftIdOrThrow(fieldId));
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    switch (field) {
    case UID:
      return isSetUid();
    case ITEM_NUMBER:
      return isSetItemNumber();
    case RESERVE_QUANTITY:
      return isSetReserveQuantity();
    case ORDER_NUMBER:
      return isSetOrderNumber();
    case FROM_ID:
      return isSetFromId();
    }
    throw new IllegalStateException();
  }

  public boolean isSet(int fieldID) {
    return isSet(_Fields.findByThriftIdOrThrow(fieldID));
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof itemReservation)
      return this.equals((itemReservation)that);
    return false;
  }

  public boolean equals(itemReservation that) {
    if (that == null)
      return false;

    boolean this_present_uid = true;
    boolean that_present_uid = true;
    if (this_present_uid || that_present_uid) {
      if (!(this_present_uid && that_present_uid))
        return false;
      if (this.uid != that.uid)
        return false;
    }

    boolean this_present_itemNumber = true && this.isSetItemNumber();
    boolean that_present_itemNumber = true && that.isSetItemNumber();
    if (this_present_itemNumber || that_present_itemNumber) {
      if (!(this_present_itemNumber && that_present_itemNumber))
        return false;
      if (!this.itemNumber.equals(that.itemNumber))
        return false;
    }

    boolean this_present_reserveQuantity = true;
    boolean that_present_reserveQuantity = true;
    if (this_present_reserveQuantity || that_present_reserveQuantity) {
      if (!(this_present_reserveQuantity && that_present_reserveQuantity))
        return false;
      if (this.reserveQuantity != that.reserveQuantity)
        return false;
    }

    boolean this_present_orderNumber = true && this.isSetOrderNumber();
    boolean that_present_orderNumber = true && that.isSetOrderNumber();
    if (this_present_orderNumber || that_present_orderNumber) {
      if (!(this_present_orderNumber && that_present_orderNumber))
        return false;
      if (!this.orderNumber.equals(that.orderNumber))
        return false;
    }

    boolean this_present_fromId = true && this.isSetFromId();
    boolean that_present_fromId = true && that.isSetFromId();
    if (this_present_fromId || that_present_fromId) {
      if (!(this_present_fromId && that_present_fromId))
        return false;
      if (!this.fromId.equals(that.fromId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(itemReservation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    itemReservation typedOther = (itemReservation)other;

    lastComparison = Boolean.valueOf(isSetUid()).compareTo(typedOther.isSetUid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUid()) {      lastComparison = TBaseHelper.compareTo(uid, typedOther.uid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetItemNumber()).compareTo(typedOther.isSetItemNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetItemNumber()) {      lastComparison = TBaseHelper.compareTo(itemNumber, typedOther.itemNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReserveQuantity()).compareTo(typedOther.isSetReserveQuantity());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReserveQuantity()) {      lastComparison = TBaseHelper.compareTo(reserveQuantity, typedOther.reserveQuantity);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOrderNumber()).compareTo(typedOther.isSetOrderNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOrderNumber()) {      lastComparison = TBaseHelper.compareTo(orderNumber, typedOther.orderNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFromId()).compareTo(typedOther.isSetFromId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFromId()) {      lastComparison = TBaseHelper.compareTo(fromId, typedOther.fromId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // UID
          if (field.type == TType.I32) {
            this.uid = iprot.readI32();
            setUidIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // ITEM_NUMBER
          if (field.type == TType.STRING) {
            this.itemNumber = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // RESERVE_QUANTITY
          if (field.type == TType.I32) {
            this.reserveQuantity = iprot.readI32();
            setReserveQuantityIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // ORDER_NUMBER
          if (field.type == TType.STRING) {
            this.orderNumber = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // FROM_ID
          if (field.type == TType.STRING) {
            this.fromId = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    oprot.writeFieldBegin(UID_FIELD_DESC);
    oprot.writeI32(this.uid);
    oprot.writeFieldEnd();
    if (this.itemNumber != null) {
      oprot.writeFieldBegin(ITEM_NUMBER_FIELD_DESC);
      oprot.writeString(this.itemNumber);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(RESERVE_QUANTITY_FIELD_DESC);
    oprot.writeI32(this.reserveQuantity);
    oprot.writeFieldEnd();
    if (this.orderNumber != null) {
      oprot.writeFieldBegin(ORDER_NUMBER_FIELD_DESC);
      oprot.writeString(this.orderNumber);
      oprot.writeFieldEnd();
    }
    if (this.fromId != null) {
      oprot.writeFieldBegin(FROM_ID_FIELD_DESC);
      oprot.writeString(this.fromId);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("itemReservation(");
    boolean first = true;

    sb.append("uid:");
    sb.append(this.uid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("itemNumber:");
    if (this.itemNumber == null) {
      sb.append("null");
    } else {
      sb.append(this.itemNumber);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("reserveQuantity:");
    sb.append(this.reserveQuantity);
    first = false;
    if (!first) sb.append(", ");
    sb.append("orderNumber:");
    if (this.orderNumber == null) {
      sb.append("null");
    } else {
      sb.append(this.orderNumber);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("fromId:");
    if (this.fromId == null) {
      sb.append("null");
    } else {
      sb.append(this.fromId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

