/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.focaplo.supverinventory.rpc;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;

public class QuantityUpdate implements TBase<QuantityUpdate._Fields>, java.io.Serializable, Cloneable, Comparable<QuantityUpdate> {
  private static final TStruct STRUCT_DESC = new TStruct("QuantityUpdate");

  private static final TField UID_FIELD_DESC = new TField("uid", TType.I32, (short)1);
  private static final TField ITEM_NUMBER_FIELD_DESC = new TField("itemNumber", TType.STRING, (short)2);
  private static final TField QUANTITY_CHANGE_FIELD_DESC = new TField("quantityChange", TType.I32, (short)3);
  private static final TField WAREHOUSE_NUMBER_FIELD_DESC = new TField("warehouseNumber", TType.STRING, (short)4);
  private static final TField REASON_FIELD_DESC = new TField("reason", TType.STRING, (short)5);

  public int uid;
  public String itemNumber;
  public int quantityChange;
  public String warehouseNumber;
  public String reason;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    UID((short)1, "uid"),
    ITEM_NUMBER((short)2, "itemNumber"),
    QUANTITY_CHANGE((short)3, "quantityChange"),
    WAREHOUSE_NUMBER((short)4, "warehouseNumber"),
    REASON((short)5, "reason");

    private static final Map<Integer, _Fields> byId = new HashMap<Integer, _Fields>();
    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byId.put((int)field._thriftId, field);
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      return byId.get(fieldId);
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __UID_ISSET_ID = 0;
  private static final int __QUANTITYCHANGE_ISSET_ID = 1;
  private BitSet __isset_bit_vector = new BitSet(2);

  public static final Map<_Fields, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new EnumMap<_Fields, FieldMetaData>(_Fields.class) {{
    put(_Fields.UID, new FieldMetaData("uid", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I32)));
    put(_Fields.ITEM_NUMBER, new FieldMetaData("itemNumber", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    put(_Fields.QUANTITY_CHANGE, new FieldMetaData("quantityChange", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I32)));
    put(_Fields.WAREHOUSE_NUMBER, new FieldMetaData("warehouseNumber", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    put(_Fields.REASON, new FieldMetaData("reason", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
  }});

  static {
    FieldMetaData.addStructMetaDataMap(QuantityUpdate.class, metaDataMap);
  }

  public QuantityUpdate() {
  }

  public QuantityUpdate(
    int uid,
    String itemNumber,
    int quantityChange,
    String warehouseNumber,
    String reason)
  {
    this();
    this.uid = uid;
    setUidIsSet(true);
    this.itemNumber = itemNumber;
    this.quantityChange = quantityChange;
    setQuantityChangeIsSet(true);
    this.warehouseNumber = warehouseNumber;
    this.reason = reason;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QuantityUpdate(QuantityUpdate other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.uid = other.uid;
    if (other.isSetItemNumber()) {
      this.itemNumber = other.itemNumber;
    }
    this.quantityChange = other.quantityChange;
    if (other.isSetWarehouseNumber()) {
      this.warehouseNumber = other.warehouseNumber;
    }
    if (other.isSetReason()) {
      this.reason = other.reason;
    }
  }

  public QuantityUpdate deepCopy() {
    return new QuantityUpdate(this);
  }

  @Deprecated
  public QuantityUpdate clone() {
    return new QuantityUpdate(this);
  }

  public int getUid() {
    return this.uid;
  }

  public QuantityUpdate setUid(int uid) {
    this.uid = uid;
    setUidIsSet(true);
    return this;
  }

  public void unsetUid() {
    __isset_bit_vector.clear(__UID_ISSET_ID);
  }

  /** Returns true if field uid is set (has been asigned a value) and false otherwise */
  public boolean isSetUid() {
    return __isset_bit_vector.get(__UID_ISSET_ID);
  }

  public void setUidIsSet(boolean value) {
    __isset_bit_vector.set(__UID_ISSET_ID, value);
  }

  public String getItemNumber() {
    return this.itemNumber;
  }

  public QuantityUpdate setItemNumber(String itemNumber) {
    this.itemNumber = itemNumber;
    return this;
  }

  public void unsetItemNumber() {
    this.itemNumber = null;
  }

  /** Returns true if field itemNumber is set (has been asigned a value) and false otherwise */
  public boolean isSetItemNumber() {
    return this.itemNumber != null;
  }

  public void setItemNumberIsSet(boolean value) {
    if (!value) {
      this.itemNumber = null;
    }
  }

  public int getQuantityChange() {
    return this.quantityChange;
  }

  public QuantityUpdate setQuantityChange(int quantityChange) {
    this.quantityChange = quantityChange;
    setQuantityChangeIsSet(true);
    return this;
  }

  public void unsetQuantityChange() {
    __isset_bit_vector.clear(__QUANTITYCHANGE_ISSET_ID);
  }

  /** Returns true if field quantityChange is set (has been asigned a value) and false otherwise */
  public boolean isSetQuantityChange() {
    return __isset_bit_vector.get(__QUANTITYCHANGE_ISSET_ID);
  }

  public void setQuantityChangeIsSet(boolean value) {
    __isset_bit_vector.set(__QUANTITYCHANGE_ISSET_ID, value);
  }

  public String getWarehouseNumber() {
    return this.warehouseNumber;
  }

  public QuantityUpdate setWarehouseNumber(String warehouseNumber) {
    this.warehouseNumber = warehouseNumber;
    return this;
  }

  public void unsetWarehouseNumber() {
    this.warehouseNumber = null;
  }

  /** Returns true if field warehouseNumber is set (has been asigned a value) and false otherwise */
  public boolean isSetWarehouseNumber() {
    return this.warehouseNumber != null;
  }

  public void setWarehouseNumberIsSet(boolean value) {
    if (!value) {
      this.warehouseNumber = null;
    }
  }

  public String getReason() {
    return this.reason;
  }

  public QuantityUpdate setReason(String reason) {
    this.reason = reason;
    return this;
  }

  public void unsetReason() {
    this.reason = null;
  }

  /** Returns true if field reason is set (has been asigned a value) and false otherwise */
  public boolean isSetReason() {
    return this.reason != null;
  }

  public void setReasonIsSet(boolean value) {
    if (!value) {
      this.reason = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case UID:
      if (value == null) {
        unsetUid();
      } else {
        setUid((Integer)value);
      }
      break;

    case ITEM_NUMBER:
      if (value == null) {
        unsetItemNumber();
      } else {
        setItemNumber((String)value);
      }
      break;

    case QUANTITY_CHANGE:
      if (value == null) {
        unsetQuantityChange();
      } else {
        setQuantityChange((Integer)value);
      }
      break;

    case WAREHOUSE_NUMBER:
      if (value == null) {
        unsetWarehouseNumber();
      } else {
        setWarehouseNumber((String)value);
      }
      break;

    case REASON:
      if (value == null) {
        unsetReason();
      } else {
        setReason((String)value);
      }
      break;

    }
  }

  public void setFieldValue(int fieldID, Object value) {
    setFieldValue(_Fields.findByThriftIdOrThrow(fieldID), value);
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case UID:
      return new Integer(getUid());

    case ITEM_NUMBER:
      return getItemNumber();

    case QUANTITY_CHANGE:
      return new Integer(getQuantityChange());

    case WAREHOUSE_NUMBER:
      return getWarehouseNumber();

    case REASON:
      return getReason();

    }
    throw new IllegalStateException();
  }

  public Object getFieldValue(int fieldId) {
    return getFieldValue(_Fields.findByThriftIdOrThrow(fieldId));
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    switch (field) {
    case UID:
      return isSetUid();
    case ITEM_NUMBER:
      return isSetItemNumber();
    case QUANTITY_CHANGE:
      return isSetQuantityChange();
    case WAREHOUSE_NUMBER:
      return isSetWarehouseNumber();
    case REASON:
      return isSetReason();
    }
    throw new IllegalStateException();
  }

  public boolean isSet(int fieldID) {
    return isSet(_Fields.findByThriftIdOrThrow(fieldID));
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QuantityUpdate)
      return this.equals((QuantityUpdate)that);
    return false;
  }

  public boolean equals(QuantityUpdate that) {
    if (that == null)
      return false;

    boolean this_present_uid = true;
    boolean that_present_uid = true;
    if (this_present_uid || that_present_uid) {
      if (!(this_present_uid && that_present_uid))
        return false;
      if (this.uid != that.uid)
        return false;
    }

    boolean this_present_itemNumber = true && this.isSetItemNumber();
    boolean that_present_itemNumber = true && that.isSetItemNumber();
    if (this_present_itemNumber || that_present_itemNumber) {
      if (!(this_present_itemNumber && that_present_itemNumber))
        return false;
      if (!this.itemNumber.equals(that.itemNumber))
        return false;
    }

    boolean this_present_quantityChange = true;
    boolean that_present_quantityChange = true;
    if (this_present_quantityChange || that_present_quantityChange) {
      if (!(this_present_quantityChange && that_present_quantityChange))
        return false;
      if (this.quantityChange != that.quantityChange)
        return false;
    }

    boolean this_present_warehouseNumber = true && this.isSetWarehouseNumber();
    boolean that_present_warehouseNumber = true && that.isSetWarehouseNumber();
    if (this_present_warehouseNumber || that_present_warehouseNumber) {
      if (!(this_present_warehouseNumber && that_present_warehouseNumber))
        return false;
      if (!this.warehouseNumber.equals(that.warehouseNumber))
        return false;
    }

    boolean this_present_reason = true && this.isSetReason();
    boolean that_present_reason = true && that.isSetReason();
    if (this_present_reason || that_present_reason) {
      if (!(this_present_reason && that_present_reason))
        return false;
      if (!this.reason.equals(that.reason))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(QuantityUpdate other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    QuantityUpdate typedOther = (QuantityUpdate)other;

    lastComparison = Boolean.valueOf(isSetUid()).compareTo(typedOther.isSetUid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUid()) {      lastComparison = TBaseHelper.compareTo(uid, typedOther.uid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetItemNumber()).compareTo(typedOther.isSetItemNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetItemNumber()) {      lastComparison = TBaseHelper.compareTo(itemNumber, typedOther.itemNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQuantityChange()).compareTo(typedOther.isSetQuantityChange());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuantityChange()) {      lastComparison = TBaseHelper.compareTo(quantityChange, typedOther.quantityChange);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWarehouseNumber()).compareTo(typedOther.isSetWarehouseNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWarehouseNumber()) {      lastComparison = TBaseHelper.compareTo(warehouseNumber, typedOther.warehouseNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReason()).compareTo(typedOther.isSetReason());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReason()) {      lastComparison = TBaseHelper.compareTo(reason, typedOther.reason);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // UID
          if (field.type == TType.I32) {
            this.uid = iprot.readI32();
            setUidIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // ITEM_NUMBER
          if (field.type == TType.STRING) {
            this.itemNumber = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // QUANTITY_CHANGE
          if (field.type == TType.I32) {
            this.quantityChange = iprot.readI32();
            setQuantityChangeIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // WAREHOUSE_NUMBER
          if (field.type == TType.STRING) {
            this.warehouseNumber = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // REASON
          if (field.type == TType.STRING) {
            this.reason = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    oprot.writeFieldBegin(UID_FIELD_DESC);
    oprot.writeI32(this.uid);
    oprot.writeFieldEnd();
    if (this.itemNumber != null) {
      oprot.writeFieldBegin(ITEM_NUMBER_FIELD_DESC);
      oprot.writeString(this.itemNumber);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(QUANTITY_CHANGE_FIELD_DESC);
    oprot.writeI32(this.quantityChange);
    oprot.writeFieldEnd();
    if (this.warehouseNumber != null) {
      oprot.writeFieldBegin(WAREHOUSE_NUMBER_FIELD_DESC);
      oprot.writeString(this.warehouseNumber);
      oprot.writeFieldEnd();
    }
    if (this.reason != null) {
      oprot.writeFieldBegin(REASON_FIELD_DESC);
      oprot.writeString(this.reason);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("QuantityUpdate(");
    boolean first = true;

    sb.append("uid:");
    sb.append(this.uid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("itemNumber:");
    if (this.itemNumber == null) {
      sb.append("null");
    } else {
      sb.append(this.itemNumber);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("quantityChange:");
    sb.append(this.quantityChange);
    first = false;
    if (!first) sb.append(", ");
    sb.append("warehouseNumber:");
    if (this.warehouseNumber == null) {
      sb.append("null");
    } else {
      sb.append(this.warehouseNumber);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("reason:");
    if (this.reason == null) {
      sb.append("null");
    } else {
      sb.append(this.reason);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

